language: c
install:
  - git config --global user.email "krlmlr+autobuild@mailbox.org"
  - git config --global user.name "AutoBuild"

script:
  - make
  - git status
  - git add -f out
  - git checkout master
  - git log
  - git commit -C HEAD
  - git commit --amend -m "Update binaries"
